import { expect, test } from "@playwright/test";
import { ENCOUNTER_ID } from "./fixtures.js";

/** Epistemic guards at the HTTP layer (work order §2). */
test.describe("epistemic guards", () => {
  test("no route returns a global edge list: /api/graph does not exist", async ({ request }) => {
    const response = await request.get("/api/graph");
    expect(response.status()).toBe(404);
  });

  test("map version URLs are immutable: two fetches of the same URL serve identical content", async ({ request }) => {
    const url = `/encounters/${ENCOUNTER_ID}/maps/provenance-v1@1/export.json`;
    const a = await (await request.get(url)).json();
    const b = await (await request.get(url)).json();
    expect(a).toEqual(b);
    expect(a.content_hash).toBe(b.content_hash);
    expect(a.accessible_summary).toBe(b.accessible_summary);
  });

  test("map version export.json is real JSON with a stable content_hash and matches the HTML page's displayed hash", async ({ page, request }) => {
    const url = `/encounters/${ENCOUNTER_ID}/maps/ensemble-transformation-v1@1`;
    const json = await (await request.get(`${url}/export.json`)).json();
    await page.goto(url);
    const citation = page.locator(".citation");
    await expect(citation).toContainText(json.content_hash);
  });

  test("/encounters/[id] shows participant statuses side by side, never merged into one shared label", async ({ page }) => {
    await page.goto(`/encounters/${ENCOUNTER_ID}`);
    const body = await page.textContent("body");
    // Meridian's and Ensemble's distinct local statuses must BOTH be visible verbatim — a
    // merged/flattened summary would drop one of these exact phrases.
    expect(body).toContain("correction applied; register revised; obligations active");
    expect(body).toContain("premiered; live-status obligation active");
  });

  test("silence rendering: 'Ulysses' appears on the encounter page ONLY inside the documented non-participation section", async ({ page }) => {
    await page.goto(`/encounters/${ENCOUNTER_ID}`);
    // `.innerText()` (not `.textContent()`): respects rendering/visibility and — critically —
    // excludes the SvelteKit hydration payload's serialized JSON at the end of <body>, which
    // would otherwise double-count every occurrence that also appears in the page's `data`.
    const fullBodyText = await page.locator("body").innerText();
    const occurrences = fullBodyText.match(/Ulysses/g) ?? [];
    expect(occurrences.length).toBeGreaterThan(0);

    const sectionText = await page.locator("section.non-participation-section").innerText();
    const sectionOccurrences = sectionText.match(/Ulysses/g) ?? [];

    // Every "Ulysses" mention on the page is accounted for inside the non-participation block.
    expect(sectionOccurrences.length).toBe(occurrences.length);
  });

  test("unsupported/non-core event types remain visible, never silently normalised (contract.published on the provenance chain)", async ({ page }) => {
    await page.goto(`/encounters/${ENCOUNTER_ID}/maps/provenance-v1@1`);
    const chip = page.locator(".type-chip", { hasText: "contract.published" });
    await expect(chip).toBeVisible();
    await expect(chip).toHaveClass(/type-chip--local/);
    await expect(page.getByText("not a core protocol type")).toBeVisible();
  });

  test("obligations, exclusions and unknown-type counts are all present in the accessible lens manifest (no expert knowledge required)", async ({ page }) => {
    await page.goto(`/encounters/${ENCOUNTER_ID}/maps/ensemble-transformation-v1@1`);
    const details = page.locator("details.lens-manifest");
    await details.locator("summary").click();
    await expect(details).toContainText("Excluded");
    await expect(details).toContainText("Unknown types");
    await expect(details).toContainText("Generated by");
  });

  test("source and derivative objects both link to their sovereign home archives", async ({ page }) => {
    await page.goto("/objects/meridian/instrument-001");
    const doorway = page.locator(".doorway-link");
    await expect(doorway).toHaveAttribute("href", /github\.com\/frankbueltge\/field-research/);

    await page.goto("/objects/ensemble/native-speaker");
    const doorway2 = page.locator(".doorway-link");
    await expect(doorway2).toHaveAttribute("href", /github\.com\/frankbueltge\/studio/);
  });

  test("no KPI/dashboard class names leak into the markup (visual prohibitions, spec 09 §7)", async ({ page }) => {
    await page.goto(`/encounters/${ENCOUNTER_ID}`);
    const html = await page.content();
    for (const forbidden of ["kpi", "dashboard-grid", "glassmorphism", "agent-avatar"]) {
      expect(html.toLowerCase()).not.toContain(forbidden);
    }
  });
});
